<a href="https://colab.research.google.com/github/fathimaa-afreen/day-1-scientific-python/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
b = np.array([[1,2,3],[4,5,6],[2,3,4]])


[1 2 3 4 5]


In [ ]:
zeros = np.zeros((2,3))
ones = np.ones((3,3))
print(ones)




[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
identity = np.eye(3)
print(identity)




[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [ ]:
rand = np.random.rand(2,3)
print(rand)

[[0.25320631 0.40385495 0.15911342]
 [0.9641085  0.64077345 0.18974452]]


In [ ]:
rand = np.random.rand(4,3)
print(rand)

[[0.57557773 0.9473601  0.41680062]
 [0.20959432 0.8480117  0.66430168]
 [0.76743349 0.53322804 0.52850622]
 [0.96002281 0.01265957 0.49138128]]


In [ ]:
b = np.array([[1,2,3],[4,5,6],[2,3,4]])
print(b)
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

[[1 2 3]
 [4 5 6]
 [2 3 4]]
(3, 3)
2
9
int64


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

sum_arr = arr1 + arr2
print(sum_arr)

sub_arr = arr1 - arr2
print(sub_arr)

mul_arr = arr1 * arr2
print(mul_arr)

div_arr = arr1 / arr2
print(div_arr)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
z = np.array([[1,2,3],[0,8,9],[10,20,23]])
print(z)


[[ 1  2  3]
 [ 0  8  9]
 [10 20 23]]


In [ ]:
print(z[0:1:])

[[1 2 3]]


In [ ]:
print(z[2:3:])

[[10 20 23]]


In [ ]:
print(z[:,0:1])

[[ 1]
 [ 0]
 [10]]


In [ ]:
print(z[1,0])

0


In [ ]:
print(z[2,:])

[10 20 23]


In [ ]:
print(z[0,:])

[1 2 3]


In [ ]:
print(z[2,1])

20


In [ ]:
print(z[:,1])

[ 2  8 20]


In [ ]:
print(z[2,2])

23


In [ ]:
print(z[1,2])

9
