<a href="https://colab.research.google.com/github/fathimaa-afreen/day-1-scientific-python/blob/main/Day_2_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr[:,0])

[1 4 7]


In [ ]:
print(arr[2])

[7 8 9]


In [ ]:
print(arr[1,1])

5


In [ ]:
print(arr[1,0])

4


In [ ]:
print(np.diag(arr))

[1 5 9]


In [ ]:
print(arr[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
arr = np.arange(1, 10).reshape(3, 3)
arr[arr % 2 == 0] = 0
print(arr)

[[1 0 3]
 [0 5 0]
 [7 0 9]]


In [ ]:
print(arr.shape)

(3, 3)


In [ ]:
print(arr.size)

9


In [ ]:
print(arr.ndim)

2


In [ ]:
print(arr.dtype)

int64


In [ ]:
print(arr.sum())

45


In [ ]:
print(arr.mean())

5.0


In [ ]:
print(arr.max())

9


In [ ]:
print(arr.min())

1


In [ ]:
arr = np.arange(1,25)
print(arr.reshape(6,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(arr.reshape(2,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
arr = np.random.randint(1,101,20)
print(arr)
print( np.mean(arr))
print( np.median(arr))
print( np.std(arr))

[64 64 94 34 44 76 65 52  1 25 16 85 57 74  1 83 99 76 27 55]
54.6
60.5
28.508595195133694


In [ ]:
arr = np.random.randint(1, 101, 20)

print(arr[arr > 50])

[ 88  70  56  76 100  68  79  87]


In [ ]:
new_arr = arr.copy()
new_arr[new_arr < 50] = 50
print(new_arr)

[64 64 94 50 50 76 65 52 50 50 50 85 57 74 50 83 99 76 50 55]


In [ ]:
A= np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[9,8,7],
              [6,5,4],
              [3,2,1]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Matrix Multiplication:\n", A @ B)
print("Transpose of A:\n", A.T)
print("Transpose of B:\n", B.T)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of B:
 [[9 6 3]
 [8 5 2]
 [7 4 1]]
